name: firebaseui
description: A new flutter plugin project.

flutter:
  plugin:
    androidPackage: com.yourcompany.firebaseui
    pluginClass: FirebaseuiPlugin

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: "^0.0.3+1"
